package view;

import control.KaryawanControl;
import control.LapanganControl;
import control.PenyewaControl;
import control.PeminjamanLapanganControl;
import control.TransaksiControl;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import java.util.Date;
import model.Karyawan;
import model.Lapangan;
import model.Penyewa;
import model.PeminjamanLapangan;
import model.Transaksi;
import java.text.SimpleDateFormat;

public class ViewTransaksi extends javax.swing.JFrame {
    private KaryawanControl kControl;
    private LapanganControl lControl;
    private PenyewaControl pControl;
    private TransaksiControl tControl;
    private PeminjamanLapanganControl plControl;
    private Karyawan karyawan;
    private Lapangan lapangan;
    private PeminjamanLapangan peminjamanLap;
    private Penyewa penyewa;
    private Transaksi transaksi;
    String action = null;
    List<PeminjamanLapangan> listPL;
    List<Lapangan> listL;
    int selectedId;
    int totalHarga = 30000;
    
    public ViewTransaksi(PeminjamanLapangan pl) {
        initComponents();
        this.peminjamanLap = pl;
        //setComponent(false);
        plControl = new PeminjamanLapanganControl();
        pControl = new PenyewaControl();
        tControl = new TransaksiControl();
        kControl = new KaryawanControl();
        lControl = new LapanganControl();
        //showTransaksi();     
        idTransaksiOutput.setText(Integer.toString(tControl.getLastId()));
        tanggalOutput.setText(pl.getTanggal());
        outputNama.setText(pl.getPenyewa().getNama());
        noTelpOutput.setText(pl.getPenyewa().getNotelp());
        totalOutput.setText(Integer.toString(totalHarga));
        
        outputNamaLap.setText(pl.getLapangan().getNama1());
        outputFasilitasLap.setText(pl.getLapangan().getFasilitas());
        
        outputStatusLap.setText(pl.getLapangan().getStatusLapangan());
        outputTanggalPinjam.setText(pl.getTanggal());
        outputJamPinjam.setText(pl.getLamaPeminjaman());
        //outputStatusBayar.setText(transaksi.getStatusPembayaran());
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        basePanel = new javax.swing.JPanel();
        backIcon = new javax.swing.JLabel();
        invoicePanel = new javax.swing.JPanel();
        logoPanel = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        brandLabel = new javax.swing.JLabel();
        alamatLabel = new javax.swing.JLabel();
        noTelpLabel = new javax.swing.JLabel();
        invoiceLabel = new javax.swing.JLabel();
        kepadaLabel = new javax.swing.JLabel();
        outputNama = new javax.swing.JTextField();
        noTelpOutput = new javax.swing.JTextField();
        idTransaksiOutput = new javax.swing.JTextField();
        tanggalOutput = new javax.swing.JTextField();
        idTransaksiLabel = new javax.swing.JLabel();
        tanggalLabel = new javax.swing.JLabel();
        detailPanel = new javax.swing.JPanel();
        namaLapLabel = new javax.swing.JLabel();
        outputNamaLap = new javax.swing.JTextField();
        outputFasilitasLap = new javax.swing.JTextField();
        fasilitasLap = new javax.swing.JLabel();
        statusLap = new javax.swing.JLabel();
        outputStatusLap = new javax.swing.JTextField();
        tanggalPinjam = new javax.swing.JLabel();
        outputTanggalPinjam = new javax.swing.JTextField();
        jamPinjam = new javax.swing.JLabel();
        outputJamPinjam = new javax.swing.JTextField();
        statusBayar = new javax.swing.JLabel();
        outputStatusBayar = new javax.swing.JTextField();
        bayarPanel = new javax.swing.JPanel();
        totalLabel = new javax.swing.JLabel();
        masukkanUangLabel = new javax.swing.JLabel();
        totalOutput = new javax.swing.JTextField();
        uangInput = new javax.swing.JTextField();
        bayarBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        basePanel.setBackground(new java.awt.Color(164, 180, 196));

        backIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/backIcon.png"))); // NOI18N
        backIcon.setText(" ");
        backIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backIconMouseClicked(evt);
            }
        });

        invoicePanel.setBackground(new java.awt.Color(182, 192, 202));
        invoicePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(62, 73, 97), 3, true));
        invoicePanel.setForeground(new java.awt.Color(182, 192, 202));

        logoPanel.setBackground(new java.awt.Color(224, 235, 253));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/sportFieldIcon 1.png"))); // NOI18N
        icon.setText("jLabel1");

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 61, Short.MAX_VALUE)
                .addContainerGap())
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        brandLabel.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        brandLabel.setForeground(new java.awt.Color(88, 111, 132));
        brandLabel.setText("Atma Footbal Center");

        alamatLabel.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        alamatLabel.setForeground(new java.awt.Color(0, 0, 0));
        alamatLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alamatLabel.setText("Jl. Ngoding Sangat Menyenangkan");

        noTelpLabel.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        noTelpLabel.setForeground(new java.awt.Color(0, 0, 0));
        noTelpLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noTelpLabel.setText("(021) - 0101 101 / 0810101010101");

        invoiceLabel.setFont(new java.awt.Font("STZhongsong", 1, 36)); // NOI18N
        invoiceLabel.setForeground(new java.awt.Color(0, 0, 0));
        invoiceLabel.setText("TRANSAKSI");

        kepadaLabel.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        kepadaLabel.setForeground(new java.awt.Color(0, 0, 0));
        kepadaLabel.setText("Penyewa");

        outputNama.setBackground(new java.awt.Color(171, 180, 190));
        outputNama.setText("   ");
        outputNama.setBorder(null);

        noTelpOutput.setBackground(new java.awt.Color(171, 180, 190));
        noTelpOutput.setText("   ");
        noTelpOutput.setBorder(null);

        idTransaksiOutput.setBackground(new java.awt.Color(171, 180, 190));
        idTransaksiOutput.setText("    ");
        idTransaksiOutput.setBorder(null);
        idTransaksiOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTransaksiOutputActionPerformed(evt);
            }
        });

        tanggalOutput.setBackground(new java.awt.Color(171, 180, 190));
        tanggalOutput.setText("   ");
        tanggalOutput.setBorder(null);

        idTransaksiLabel.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        idTransaksiLabel.setForeground(new java.awt.Color(0, 0, 0));
        idTransaksiLabel.setText("No Nota :");

        tanggalLabel.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        tanggalLabel.setForeground(new java.awt.Color(0, 0, 0));
        tanggalLabel.setText("Tanggal :");

        detailPanel.setBackground(new java.awt.Color(171, 180, 190));
        detailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "  Detail Pesanan  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Mongolian Baiti", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        namaLapLabel.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        namaLapLabel.setForeground(new java.awt.Color(0, 0, 0));
        namaLapLabel.setText("Nama Lapangan       :");

        outputNamaLap.setBackground(new java.awt.Color(182, 192, 202));
        outputNamaLap.setText("    ");
        outputNamaLap.setBorder(null);
        outputNamaLap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputNamaLapActionPerformed(evt);
            }
        });

        outputFasilitasLap.setBackground(new java.awt.Color(182, 192, 202));
        outputFasilitasLap.setText("    ");
        outputFasilitasLap.setBorder(null);
        outputFasilitasLap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputFasilitasLapActionPerformed(evt);
            }
        });

        fasilitasLap.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        fasilitasLap.setForeground(new java.awt.Color(0, 0, 0));
        fasilitasLap.setText("Fasilitas                   :");

        statusLap.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        statusLap.setForeground(new java.awt.Color(0, 0, 0));
        statusLap.setText("Status Lapangan       : ");

        outputStatusLap.setBackground(new java.awt.Color(182, 192, 202));
        outputStatusLap.setText("    ");
        outputStatusLap.setBorder(null);
        outputStatusLap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputStatusLapActionPerformed(evt);
            }
        });

        tanggalPinjam.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        tanggalPinjam.setForeground(new java.awt.Color(0, 0, 0));
        tanggalPinjam.setText("Tanggal Peminjaman :");

        outputTanggalPinjam.setBackground(new java.awt.Color(182, 192, 202));
        outputTanggalPinjam.setText("    ");
        outputTanggalPinjam.setBorder(null);
        outputTanggalPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputTanggalPinjamActionPerformed(evt);
            }
        });

        jamPinjam.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        jamPinjam.setForeground(new java.awt.Color(0, 0, 0));
        jamPinjam.setText("Jam Peminjaman       : ");

        outputJamPinjam.setBackground(new java.awt.Color(182, 192, 202));
        outputJamPinjam.setText("    ");
        outputJamPinjam.setBorder(null);
        outputJamPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputJamPinjamActionPerformed(evt);
            }
        });

        statusBayar.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        statusBayar.setForeground(new java.awt.Color(0, 0, 0));
        statusBayar.setText("Status Pembayaran    :");

        outputStatusBayar.setBackground(new java.awt.Color(182, 192, 202));
        outputStatusBayar.setText("    ");
        outputStatusBayar.setBorder(null);
        outputStatusBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputStatusBayarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout detailPanelLayout = new javax.swing.GroupLayout(detailPanel);
        detailPanel.setLayout(detailPanelLayout);
        detailPanelLayout.setHorizontalGroup(
            detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailPanelLayout.createSequentialGroup()
                        .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fasilitasLap, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(namaLapLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(outputFasilitasLap, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jamPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(outputJamPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(detailPanelLayout.createSequentialGroup()
                        .addComponent(statusLap, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(outputStatusLap, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(statusBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(outputStatusBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(detailPanelLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(outputNamaLap, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tanggalPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(outputTanggalPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        detailPanelLayout.setVerticalGroup(
            detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputNamaLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaLapLabel)
                    .addComponent(tanggalPinjam)
                    .addComponent(outputTanggalPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fasilitasLap)
                    .addComponent(outputFasilitasLap, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jamPinjam)
                    .addComponent(outputJamPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(statusBayar)
                        .addComponent(outputStatusBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(statusLap)
                        .addComponent(outputStatusLap, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        bayarPanel.setBackground(new java.awt.Color(171, 180, 190));
        bayarPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "  Pembayaran  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Mongolian Baiti", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        totalLabel.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        totalLabel.setForeground(new java.awt.Color(0, 0, 0));
        totalLabel.setText("Total                  :");

        masukkanUangLabel.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        masukkanUangLabel.setForeground(new java.awt.Color(0, 0, 0));
        masukkanUangLabel.setText("Masukkan Uang : ");

        totalOutput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalOutput.setText(" ");

        uangInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        uangInput.setText(" ");
        uangInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uangInputActionPerformed(evt);
            }
        });

        bayarBtn.setText("Bayar");
        bayarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bayarPanelLayout = new javax.swing.GroupLayout(bayarPanel);
        bayarPanel.setLayout(bayarPanelLayout);
        bayarPanelLayout.setHorizontalGroup(
            bayarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bayarPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(bayarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(masukkanUangLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bayarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uangInput, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bayarPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bayarBtn)
                .addGap(18, 18, 18)
                .addComponent(cancelBtn)
                .addContainerGap())
        );
        bayarPanelLayout.setVerticalGroup(
            bayarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bayarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bayarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalLabel)
                    .addComponent(totalOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bayarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(masukkanUangLabel)
                    .addComponent(uangInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bayarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bayarBtn)
                    .addComponent(cancelBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout invoicePanelLayout = new javax.swing.GroupLayout(invoicePanel);
        invoicePanel.setLayout(invoicePanelLayout);
        invoicePanelLayout.setHorizontalGroup(
            invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invoicePanelLayout.createSequentialGroup()
                .addGroup(invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(invoicePanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(detailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(invoicePanelLayout.createSequentialGroup()
                                .addGroup(invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(invoicePanelLayout.createSequentialGroup()
                                        .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(brandLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(noTelpLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(alamatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(invoicePanelLayout.createSequentialGroup()
                                        .addGroup(invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(idTransaksiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tanggalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(idTransaksiOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tanggalOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(162, 162, 162)
                                .addGroup(invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(invoiceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(kepadaLabel)
                                    .addComponent(outputNama)
                                    .addComponent(noTelpOutput)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, invoicePanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bayarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );
        invoicePanelLayout.setVerticalGroup(
            invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invoicePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(invoicePanelLayout.createSequentialGroup()
                        .addComponent(invoiceLabel)
                        .addGap(18, 18, 18)
                        .addComponent(kepadaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(outputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(noTelpOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(invoicePanelLayout.createSequentialGroup()
                        .addGroup(invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(invoicePanelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(brandLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alamatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(noTelpLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idTransaksiOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idTransaksiLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tanggalOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tanggalLabel))))
                .addGap(27, 27, 27)
                .addComponent(detailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bayarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout basePanelLayout = new javax.swing.GroupLayout(basePanel);
        basePanel.setLayout(basePanelLayout);
        basePanelLayout.setHorizontalGroup(
            basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basePanelLayout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addComponent(invoicePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(505, 505, 505))
            .addGroup(basePanelLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(backIcon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        basePanelLayout.setVerticalGroup(
            basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basePanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(invoicePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(backIcon)
                .addGap(78, 78, 78))
        );

        jScrollPane1.setViewportView(basePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idTransaksiOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTransaksiOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTransaksiOutputActionPerformed

    private void backIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backIconMouseClicked
        ViewBooking vb = new ViewBooking();
        this.dispose();
        vb.setVisible(true);
    }//GEN-LAST:event_backIconMouseClicked

    private void outputNamaLapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputNamaLapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputNamaLapActionPerformed

    private void bayarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarBtnActionPerformed
        if(Integer.parseInt(uangInput.getText()) < totalHarga){
            JOptionPane.showMessageDialog(null, "Uang Anda Kurang !");
        }else{
            JOptionPane.showMessageDialog(null, "Pembayaran Berhasil !\n Kembalian : " +(Integer.parseInt(uangInput.getText())-totalHarga));
            action = "Bayar";
            outputStatusBayar.setText("Lunas");
//            peminjamanLap.getLapangan().getStatusLapangan().replace("Available", "Booked");
//            lapangan.getStatusLapangan().replace("Available", "Booked");
             peminjamanLap.getLapangan().setStatusLapangan("Booked");
            lControl.updateDataLapangan(peminjamanLap.getLapangan(), peminjamanLap.getLapangan().getId());
        }
    }//GEN-LAST:event_bayarBtnActionPerformed

    private void outputFasilitasLapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputFasilitasLapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputFasilitasLapActionPerformed

    private void outputStatusLapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputStatusLapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputStatusLapActionPerformed

    private void outputTanggalPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputTanggalPinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputTanggalPinjamActionPerformed

    private void outputJamPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputJamPinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputJamPinjamActionPerformed

    private void outputStatusBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputStatusBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputStatusBayarActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void uangInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uangInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uangInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new ViewTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamatLabel;
    private javax.swing.JLabel backIcon;
    private javax.swing.JPanel basePanel;
    private javax.swing.JButton bayarBtn;
    private javax.swing.JPanel bayarPanel;
    private javax.swing.JLabel brandLabel;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JPanel detailPanel;
    private javax.swing.JLabel fasilitasLap;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel idTransaksiLabel;
    private javax.swing.JTextField idTransaksiOutput;
    private javax.swing.JLabel invoiceLabel;
    private javax.swing.JPanel invoicePanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jamPinjam;
    private javax.swing.JLabel kepadaLabel;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JLabel masukkanUangLabel;
    private javax.swing.JLabel namaLapLabel;
    private javax.swing.JLabel noTelpLabel;
    private javax.swing.JTextField noTelpOutput;
    private javax.swing.JTextField outputFasilitasLap;
    private javax.swing.JTextField outputJamPinjam;
    private javax.swing.JTextField outputNama;
    private javax.swing.JTextField outputNamaLap;
    private javax.swing.JTextField outputStatusBayar;
    private javax.swing.JTextField outputStatusLap;
    private javax.swing.JTextField outputTanggalPinjam;
    private javax.swing.JLabel statusBayar;
    private javax.swing.JLabel statusLap;
    private javax.swing.JLabel tanggalLabel;
    private javax.swing.JTextField tanggalOutput;
    private javax.swing.JLabel tanggalPinjam;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JTextField totalOutput;
    private javax.swing.JTextField uangInput;
    // End of variables declaration//GEN-END:variables
}
