package view;

import control.KaryawanControl;
import model.Karyawan;
import table.TableKaryawan;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import exception.InputKosongException;
import exception.JenisKaryawanException;

public class ViewKaryawan extends javax.swing.JFrame {
    private KaryawanControl karyawanControl;
    String action = null;
    int selectedId = 0;
    
    public ViewKaryawan() {
        initComponents();
        setComponent(false);        
        setEditDeleteBtn(false);
        karyawanControl = new KaryawanControl();
        showKaryawan();        
    }
    
    public void setComponent(boolean value){
        inputId.setEnabled(value);
        inputNama.setEnabled(value);
        inputUsia.setEnabled(value);
        inputAlamat.setEnabled(value);
        adminRBtn.setEnabled(value);
        managerRBtn.setEnabled(value);
        inputNoTelp.setEnabled(value);
        
        saveBtn.setEnabled(value);
        cancelBtn.setEnabled(value);
    }
    
    public void setEditDeleteBtn(boolean value){
        editBtn.setEnabled(value);
        deleteBtn.setEnabled(value);
    }
    
    public void clearText(){
        inputId.setText("");
        inputNama.setText("");
        inputUsia.setText("");
        inputAlamat.setText("");
        jenisKaryawanBtnGroup.clearSelection();
        inputNoTelp.setText("");
        
        searchInput.setText("");        
    }
    
    public void showKaryawan(){
        karyawanTable.setModel(karyawanControl.showKaryawan(""));
    }
    
    public void InputKosongException() throws InputKosongException{
        if(inputId.getText().isEmpty() || inputNama.getText().isEmpty() ||
           inputUsia.getText().isEmpty() || inputAlamat.getText().isEmpty() || 
           inputNoTelp.getText().isEmpty()){
           throw new InputKosongException();
        }
    }
    
    public void jenisKaryawanException() throws JenisKaryawanException{
        if(adminRBtn.isSelected() == false && managerRBtn.isSelected() ==false){
            throw new JenisKaryawanException();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jenisKaryawanBtnGroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        basePanel = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        logoPanel = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        karyawanPanel = new javax.swing.JPanel();
        karyawanIcon = new javax.swing.JLabel();
        karyawanLabel = new javax.swing.JLabel();
        lapanganPanel = new javax.swing.JPanel();
        lapanganIcon = new javax.swing.JLabel();
        lapanganLabel = new javax.swing.JLabel();
        bookingPanel = new javax.swing.JPanel();
        bookingIcon = new javax.swing.JLabel();
        bookingLabel = new javax.swing.JLabel();
        inputPanel = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        inputId = new javax.swing.JTextField();
        namaLabel = new javax.swing.JLabel();
        inputNama = new javax.swing.JTextField();
        usiaLabel = new javax.swing.JLabel();
        inputUsia = new javax.swing.JTextField();
        alamatLabel = new javax.swing.JLabel();
        inputAlamat = new javax.swing.JTextField();
        jenisLabel = new javax.swing.JLabel();
        adminRBtn = new javax.swing.JRadioButton();
        managerRBtn = new javax.swing.JRadioButton();
        noTelpLabel = new javax.swing.JLabel();
        inputNoTelp = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        outputPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        karyawanTable = new javax.swing.JTable();
        searchInput = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        basePanel.setBackground(new java.awt.Color(245, 236, 215));

        sidePanel.setBackground(new java.awt.Color(245, 236, 215));

        logoPanel.setBackground(new java.awt.Color(224, 235, 253));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/sportFieldIcon 1.png"))); // NOI18N
        icon.setText("jLabel1");

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 61, Short.MAX_VALUE)
                .addContainerGap())
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        karyawanPanel.setBackground(new java.awt.Color(139, 107, 105));
        karyawanPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                karyawanPanelMouseClicked(evt);
            }
        });

        karyawanIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        karyawanIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/karyawanIcon.png"))); // NOI18N
        karyawanIcon.setText(" ");

        karyawanLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        karyawanLabel.setForeground(new java.awt.Color(255, 255, 255));
        karyawanLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        karyawanLabel.setText("KARYAWAN");

        javax.swing.GroupLayout karyawanPanelLayout = new javax.swing.GroupLayout(karyawanPanel);
        karyawanPanel.setLayout(karyawanPanelLayout);
        karyawanPanelLayout.setHorizontalGroup(
            karyawanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(karyawanIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(karyawanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        karyawanPanelLayout.setVerticalGroup(
            karyawanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(karyawanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(karyawanIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(karyawanLabel)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        lapanganPanel.setBackground(new java.awt.Color(245, 236, 215));
        lapanganPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lapanganPanelMouseClicked(evt);
            }
        });

        lapanganIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lapanganIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/lapanganIcon.png"))); // NOI18N
        lapanganIcon.setText(" ");

        lapanganLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        lapanganLabel.setForeground(new java.awt.Color(153, 153, 153));
        lapanganLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lapanganLabel.setText("LAPANGAN");

        javax.swing.GroupLayout lapanganPanelLayout = new javax.swing.GroupLayout(lapanganPanel);
        lapanganPanel.setLayout(lapanganPanelLayout);
        lapanganPanelLayout.setHorizontalGroup(
            lapanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 169, Short.MAX_VALUE)
            .addGroup(lapanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lapanganIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addComponent(lapanganLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
        );
        lapanganPanelLayout.setVerticalGroup(
            lapanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
            .addGroup(lapanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(lapanganPanelLayout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addComponent(lapanganIcon)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lapanganLabel)
                    .addContainerGap(8, Short.MAX_VALUE)))
        );

        bookingPanel.setBackground(new java.awt.Color(245, 236, 215));
        bookingPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookingPanelMouseClicked(evt);
            }
        });

        bookingIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bookingIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/bookingIcon.png"))); // NOI18N
        bookingIcon.setText(" ");

        bookingLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        bookingLabel.setForeground(new java.awt.Color(153, 153, 153));
        bookingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bookingLabel.setText("BOOKING LAPANGAN");

        javax.swing.GroupLayout bookingPanelLayout = new javax.swing.GroupLayout(bookingPanel);
        bookingPanel.setLayout(bookingPanelLayout);
        bookingPanelLayout.setHorizontalGroup(
            bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bookingIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bookingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bookingPanelLayout.setVerticalGroup(
            bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bookingIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookingLabel)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
            .addComponent(karyawanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lapanganPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bookingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(karyawanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lapanganPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        inputPanel.setBackground(new java.awt.Color(235, 226, 205));
        inputPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(194, 186, 166), new java.awt.Color(194, 186, 166), null, null));
        inputPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        idLabel.setBackground(new java.awt.Color(77, 107, 136));
        idLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        idLabel.setForeground(new java.awt.Color(139, 107, 105));
        idLabel.setText("ID");

        inputId.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        inputId.setText(" ");
        inputId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIdActionPerformed(evt);
            }
        });

        namaLabel.setBackground(new java.awt.Color(77, 107, 136));
        namaLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        namaLabel.setForeground(new java.awt.Color(139, 107, 105));
        namaLabel.setText("Nama");

        inputNama.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        inputNama.setText(" ");
        inputNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNamaActionPerformed(evt);
            }
        });

        usiaLabel.setBackground(new java.awt.Color(77, 107, 136));
        usiaLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        usiaLabel.setForeground(new java.awt.Color(139, 107, 105));
        usiaLabel.setText("Usia");

        inputUsia.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        inputUsia.setText(" ");
        inputUsia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUsiaActionPerformed(evt);
            }
        });

        alamatLabel.setBackground(new java.awt.Color(77, 107, 136));
        alamatLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        alamatLabel.setForeground(new java.awt.Color(139, 107, 105));
        alamatLabel.setText("Alamat");

        inputAlamat.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        inputAlamat.setText(" ");
        inputAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAlamatActionPerformed(evt);
            }
        });

        jenisLabel.setBackground(new java.awt.Color(77, 107, 136));
        jenisLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jenisLabel.setForeground(new java.awt.Color(139, 107, 105));
        jenisLabel.setText("Jenis Karyawan");

        adminRBtn.setBackground(new java.awt.Color(235, 226, 205));
        jenisKaryawanBtnGroup.add(adminRBtn);
        adminRBtn.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        adminRBtn.setForeground(new java.awt.Color(255, 255, 255));
        adminRBtn.setText("Admin");

        managerRBtn.setBackground(new java.awt.Color(235, 226, 205));
        jenisKaryawanBtnGroup.add(managerRBtn);
        managerRBtn.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        managerRBtn.setForeground(new java.awt.Color(255, 255, 255));
        managerRBtn.setText("Manager");

        noTelpLabel.setBackground(new java.awt.Color(77, 107, 136));
        noTelpLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        noTelpLabel.setForeground(new java.awt.Color(139, 107, 105));
        noTelpLabel.setText("Nomor Telepon");

        inputNoTelp.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        inputNoTelp.setText(" ");
        inputNoTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNoTelpActionPerformed(evt);
            }
        });

        saveBtn.setBackground(new java.awt.Color(139, 107, 105));
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(139, 107, 105));
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputPanelLayout = new javax.swing.GroupLayout(inputPanel);
        inputPanel.setLayout(inputPanelLayout);
        inputPanelLayout.setHorizontalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(noTelpLabel)
                        .addComponent(usiaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(alamatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(namaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inputNoTelp, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                            .addComponent(inputAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                            .addComponent(inputUsia, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                            .addComponent(inputId, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                            .addComponent(inputNama, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE))
                        .addComponent(jenisLabel)
                        .addGroup(inputPanelLayout.createSequentialGroup()
                            .addComponent(adminRBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(managerRBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addComponent(cancelBtn)
                        .addGap(18, 18, 18)
                        .addComponent(saveBtn)))
                .addGap(27, 27, 27))
        );
        inputPanelLayout.setVerticalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(idLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(namaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(usiaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputUsia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(alamatLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jenisLabel)
                .addGap(10, 10, 10)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminRBtn)
                    .addComponent(managerRBtn))
                .addGap(18, 18, 18)
                .addComponent(noTelpLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(cancelBtn))
                .addGap(15, 15, 15))
        );

        outputPanel.setBackground(new java.awt.Color(235, 226, 205));
        outputPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(194, 186, 166), new java.awt.Color(194, 186, 166), null, null));

        karyawanTable.setBackground(new java.awt.Color(211, 199, 195));
        karyawanTable.setForeground(new java.awt.Color(102, 102, 102));
        karyawanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        karyawanTable.setSelectionBackground(new java.awt.Color(188, 153, 142));
        karyawanTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        karyawanTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                karyawanTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(karyawanTable);

        searchInput.setText(" ");

        searchBtn.setBackground(new java.awt.Color(139, 107, 105));
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        addBtn.setBackground(new java.awt.Color(139, 107, 105));
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        editBtn.setBackground(new java.awt.Color(139, 107, 105));
        editBtn.setForeground(new java.awt.Color(255, 255, 255));
        editBtn.setText("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(139, 107, 105));
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout outputPanelLayout = new javax.swing.GroupLayout(outputPanel);
        outputPanel.setLayout(outputPanelLayout);
        outputPanelLayout.setHorizontalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, outputPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(outputPanelLayout.createSequentialGroup()
                        .addComponent(addBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editBtn)
                        .addGap(33, 33, 33)
                        .addComponent(deleteBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, outputPanelLayout.createSequentialGroup()
                        .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchBtn))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        outputPanelLayout.setVerticalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editBtn)
                    .addComponent(deleteBtn)
                    .addComponent(addBtn))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout basePanelLayout = new javax.swing.GroupLayout(basePanel);
        basePanel.setLayout(basePanelLayout);
        basePanelLayout.setHorizontalGroup(
            basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basePanelLayout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(outputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(37, 37, 37))
        );
        basePanelLayout.setVerticalGroup(
            basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(basePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(outputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(basePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIdActionPerformed

    private void inputNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNamaActionPerformed

    private void inputUsiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUsiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUsiaActionPerformed

    private void inputAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAlamatActionPerformed

    private void inputNoTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNoTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNoTelpActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        setComponent(true);
        clearText();
        action = "Tambah";
    }//GEN-LAST:event_addBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        setComponent(true);
        inputId.setEnabled(false);
        adminRBtn.setEnabled(false);
        managerRBtn.setEnabled(false);
        action = "Ubah";
    }//GEN-LAST:event_editBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        try{
            InputKosongException();
            jenisKaryawanException();
            
            Karyawan k = null;
            if(adminRBtn.isSelected()==true){
                String jenis = "Admin";
                k = new Karyawan(inputNama.getText(), inputAlamat.getText(), jenis, inputNoTelp.getText(), Integer.parseInt(inputId.getText()), Integer.parseInt(inputUsia.getText()));
            }else{
                String jenis = "Manager";
                k = new Karyawan(inputNama.getText(), inputAlamat.getText(), jenis, inputNoTelp.getText(), Integer.parseInt(inputId.getText()), Integer.parseInt(inputUsia.getText()));
            }
            if(action.equals("Tambah")){
                karyawanControl.insertKaryawan(k);
                JOptionPane.showMessageDialog(null, "Data Berhasil Ditambahkan !");
            }else{
                karyawanControl.updateKaryawan(k,Integer.parseInt(inputId.getText()));
                JOptionPane.showMessageDialog(null, "Data Berhasil Diubah !");
            }
            clearText();
            setComponent(false);
            setEditDeleteBtn(false);
            showKaryawan();
        }catch(InputKosongException e){
            JOptionPane.showMessageDialog(this, e.message());
        }catch(JenisKaryawanException e1){
            JOptionPane.showMessageDialog(this, e1.message());
        }catch(NumberFormatException e2){
            JOptionPane.showMessageDialog(this, "Input Invalid !");
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        setComponent(false);
        setEditDeleteBtn(false);
        clearText();
        JOptionPane.showMessageDialog(null, "Batal !");
        
        karyawanTable.setModel(karyawanControl.showKaryawan(""));
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void karyawanPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_karyawanPanelMouseClicked
        ViewKaryawan vk = new ViewKaryawan();
        this.dispose();
        vk.setVisible(true);
    }//GEN-LAST:event_karyawanPanelMouseClicked

    private void lapanganPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lapanganPanelMouseClicked
        ViewLapangan vl = new ViewLapangan();
        this.dispose();
        vl.setVisible(true);
    }//GEN-LAST:event_lapanganPanelMouseClicked

    private void bookingPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingPanelMouseClicked
        ViewBooking vb = new ViewBooking();
        this.dispose();
        vb.setVisible(true);
    }//GEN-LAST:event_bookingPanelMouseClicked

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int getAnswer = JOptionPane.showConfirmDialog(rootPane, "Apakah yakin ingin menghapus data ?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        switch(getAnswer){
            case 0:
                try{
                    karyawanControl.deleteKaryawan(Integer.parseInt(inputId.getText()));
                    clearText();
                    showKaryawan();
                    setComponent(false);
                    setEditDeleteBtn(false);                    
                    JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus!");
                }catch(Exception e){
                    System.out.println("Error : " +e.getMessage());
                }
                break;
            case 1:
                JOptionPane.showMessageDialog(null, "Batal Menghapus Data!");
                break;
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void karyawanTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_karyawanTableMouseClicked
        setEditDeleteBtn(true);
        setComponent(false);
        
        int clickedRow = karyawanTable.getSelectedRow();
        TableModel tableModel = karyawanTable.getModel();
        
        inputId.setText(tableModel.getValueAt(clickedRow, 0).toString());
        inputNama.setText(tableModel.getValueAt(clickedRow, 1).toString());
        inputUsia.setText(tableModel.getValueAt(clickedRow, 2).toString());
        inputAlamat.setText(tableModel.getValueAt(clickedRow, 3).toString());
        String jenis = tableModel.getValueAt(clickedRow, 4).toString();
        inputNoTelp.setText(tableModel.getValueAt(clickedRow, 5).toString());
        
        switch(jenis){
            case "Admin":
                adminRBtn.setSelected(true);
                managerRBtn.setSelected(false);
                break;
            case "Manager":
                managerRBtn.setSelected(true);
                adminRBtn.setSelected(false);
                break;
            default :
                managerRBtn.setSelected(false);
                adminRBtn.setSelected(false);
                break;
        }        
        cancelBtn.setEnabled(true);        
    }//GEN-LAST:event_karyawanTableMouseClicked

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        setEditDeleteBtn(true);
        setComponent(false);
        
        try{
           TableKaryawan tk = karyawanControl.showKaryawan(searchInput.getText());
            if(tk.getRowCount()==0) {
                clearText();
                setEditDeleteBtn(false);
                JOptionPane.showConfirmDialog(null, "Data Tidak Ditemukan!", "Konfirmasi", JOptionPane.DEFAULT_OPTION);                
            }else{
                karyawanTable.setModel(tk);
            }
            clearText();
            cancelBtn.setEnabled(true);
        }catch(Exception e){
            System.out.println("Error : " + e.getMessage());
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JRadioButton adminRBtn;
    private javax.swing.JLabel alamatLabel;
    private javax.swing.JPanel basePanel;
    private javax.swing.JLabel bookingIcon;
    private javax.swing.JLabel bookingLabel;
    private javax.swing.JPanel bookingPanel;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField inputAlamat;
    private javax.swing.JTextField inputId;
    private javax.swing.JTextField inputNama;
    private javax.swing.JTextField inputNoTelp;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JTextField inputUsia;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.ButtonGroup jenisKaryawanBtnGroup;
    private javax.swing.JLabel jenisLabel;
    private javax.swing.JLabel karyawanIcon;
    private javax.swing.JLabel karyawanLabel;
    private javax.swing.JPanel karyawanPanel;
    private javax.swing.JTable karyawanTable;
    private javax.swing.JLabel lapanganIcon;
    private javax.swing.JLabel lapanganLabel;
    private javax.swing.JPanel lapanganPanel;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JRadioButton managerRBtn;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JLabel noTelpLabel;
    private javax.swing.JPanel outputPanel;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchInput;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JLabel usiaLabel;
    // End of variables declaration//GEN-END:variables
}
