package view;

import javax.swing.JOptionPane;
import connection.DbConnection;
import java.util.List;
import control.LapanganControl;
import dao.LapanganDAO;
import table.TableLapangan;
import model.Lapangan;
import javax.swing.table.TableModel;
import exception.InputKosongException;
import exception.JenisLapanganException;
import exception.StatusLapanganException;

public class ViewLapangan extends javax.swing.JFrame {
    private LapanganControl lapanganControl; 
    String action = null;
    int selected = 0;
    List<LapanganControl> listLapanganControl;    
    
    public ViewLapangan() {        
        initComponents();
        setComponent(false);
        setEditDeleteBtn(false);
        lapanganControl = new LapanganControl();        
        showDataLapangan();
    }
    
    public void setComponent(boolean value){
        inputId.setEnabled(value);
        inputNama.setEnabled(value);
        inputLuas.setEnabled(value);
        
        availableRBtn.setEnabled(value);
        bookedRBtn.setEnabled(value);
        sintetisRBtn.setEnabled(value);
        plurRBtn.setEnabled(value);
        bolaCBox.setEnabled(value);
        rompiCBox.setEnabled(value);
        airMineralCBox.setEnabled(value);
        
        cancelBtn.setEnabled(value);
        saveBtn.setEnabled(value);
    }
    
    public void setEditDeleteBtn(boolean value){
        editBtn.setEnabled(value);
        deleteBtn.setEnabled(value);
    }
    
    public void clearText(){
        inputId.setText("");
        inputNama.setText("");
        inputLuas.setText("");
        searchInput.setText("");
        jenisLapanganBtnGroup.clearSelection();
        statusLapanganBtnGroup.clearSelection();
        bolaCBox.setSelected(false);
        rompiCBox.setSelected(false);
        airMineralCBox.setSelected(false);
    }
    
    public void showDataLapangan(){
        lapanganTable.setModel(lapanganControl.showDataLapangan(""));
    }

    public void InputKosongException() throws InputKosongException{
        if(inputId.getText().isEmpty() || inputNama.getText().isEmpty() || inputLuas.getText().isEmpty()){
           throw new InputKosongException();
        }
    }
    
    public void jenisLapanganException() throws JenisLapanganException{
        if(sintetisRBtn.isSelected() == false && plurRBtn.isSelected() ==false){
            throw new JenisLapanganException();
        }
    }
    
    public void statusLapanganException() throws StatusLapanganException{
        if(availableRBtn.isSelected() == false && bookedRBtn.isSelected() ==false){
            throw new StatusLapanganException();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jenisLapanganBtnGroup = new javax.swing.ButtonGroup();
        statusLapanganBtnGroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        basePanel = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        logoPanel = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        karyawanPanel = new javax.swing.JPanel();
        karyawanIcon = new javax.swing.JLabel();
        karyawanLabel = new javax.swing.JLabel();
        lapanganPanel = new javax.swing.JPanel();
        lapanganIcon = new javax.swing.JLabel();
        lapanganLabel = new javax.swing.JLabel();
        bookingPanel = new javax.swing.JPanel();
        bookingIcon = new javax.swing.JLabel();
        bookingLabel = new javax.swing.JLabel();
        inputPanel = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        inputId = new javax.swing.JTextField();
        namaLabel = new javax.swing.JLabel();
        inputNama = new javax.swing.JTextField();
        luasLabel = new javax.swing.JLabel();
        inputLuas = new javax.swing.JTextField();
        alamatLabel = new javax.swing.JLabel();
        fasilitasLabel = new javax.swing.JLabel();
        statusLapanganLabel = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        sintetisRBtn = new javax.swing.JRadioButton();
        plurRBtn = new javax.swing.JRadioButton();
        bolaCBox = new javax.swing.JCheckBox();
        rompiCBox = new javax.swing.JCheckBox();
        airMineralCBox = new javax.swing.JCheckBox();
        availableRBtn = new javax.swing.JRadioButton();
        bookedRBtn = new javax.swing.JRadioButton();
        outputPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lapanganTable = new javax.swing.JTable();
        searchInput = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        basePanel.setBackground(new java.awt.Color(245, 236, 215));

        sidePanel.setBackground(new java.awt.Color(245, 236, 215));

        logoPanel.setBackground(new java.awt.Color(224, 235, 253));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/sportFieldIcon 1.png"))); // NOI18N
        icon.setText("jLabel1");

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 61, Short.MAX_VALUE)
                .addContainerGap())
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        karyawanPanel.setBackground(new java.awt.Color(245, 236, 215));
        karyawanPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                karyawanPanelMouseClicked(evt);
            }
        });

        karyawanIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        karyawanIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/karyawanIcon.png"))); // NOI18N
        karyawanIcon.setText(" ");

        karyawanLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        karyawanLabel.setForeground(new java.awt.Color(153, 153, 153));
        karyawanLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        karyawanLabel.setText("KARYAWAN");

        javax.swing.GroupLayout karyawanPanelLayout = new javax.swing.GroupLayout(karyawanPanel);
        karyawanPanel.setLayout(karyawanPanelLayout);
        karyawanPanelLayout.setHorizontalGroup(
            karyawanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(karyawanIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(karyawanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        karyawanPanelLayout.setVerticalGroup(
            karyawanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(karyawanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(karyawanIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(karyawanLabel)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        lapanganPanel.setBackground(new java.awt.Color(139, 107, 105));
        lapanganPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lapanganPanelMouseClicked(evt);
            }
        });

        lapanganIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lapanganIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/lapanganIcon.png"))); // NOI18N
        lapanganIcon.setText(" ");

        lapanganLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        lapanganLabel.setForeground(new java.awt.Color(255, 255, 255));
        lapanganLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lapanganLabel.setText("LAPANGAN");

        javax.swing.GroupLayout lapanganPanelLayout = new javax.swing.GroupLayout(lapanganPanel);
        lapanganPanel.setLayout(lapanganPanelLayout);
        lapanganPanelLayout.setHorizontalGroup(
            lapanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 169, Short.MAX_VALUE)
            .addGroup(lapanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lapanganIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addComponent(lapanganLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
        );
        lapanganPanelLayout.setVerticalGroup(
            lapanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
            .addGroup(lapanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(lapanganPanelLayout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addComponent(lapanganIcon)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lapanganLabel)
                    .addContainerGap(8, Short.MAX_VALUE)))
        );

        bookingPanel.setBackground(new java.awt.Color(245, 236, 215));
        bookingPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookingPanelMouseClicked(evt);
            }
        });

        bookingIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bookingIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/bookingIcon.png"))); // NOI18N
        bookingIcon.setText(" ");

        bookingLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        bookingLabel.setForeground(new java.awt.Color(153, 153, 153));
        bookingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bookingLabel.setText("BOOKING LAPANGAN");

        javax.swing.GroupLayout bookingPanelLayout = new javax.swing.GroupLayout(bookingPanel);
        bookingPanel.setLayout(bookingPanelLayout);
        bookingPanelLayout.setHorizontalGroup(
            bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bookingIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bookingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bookingPanelLayout.setVerticalGroup(
            bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bookingIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookingLabel)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
            .addComponent(karyawanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lapanganPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bookingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(karyawanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lapanganPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        inputPanel.setBackground(new java.awt.Color(235, 226, 205));
        inputPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(194, 186, 166), new java.awt.Color(194, 186, 166), null, null));
        inputPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        idLabel.setBackground(new java.awt.Color(77, 107, 136));
        idLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        idLabel.setForeground(new java.awt.Color(139, 107, 105));
        idLabel.setText("ID");

        inputId.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        inputId.setText(" ");
        inputId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIdActionPerformed(evt);
            }
        });

        namaLabel.setBackground(new java.awt.Color(77, 107, 136));
        namaLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        namaLabel.setForeground(new java.awt.Color(139, 107, 105));
        namaLabel.setText("Nama");

        inputNama.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        inputNama.setText(" ");
        inputNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNamaActionPerformed(evt);
            }
        });

        luasLabel.setBackground(new java.awt.Color(77, 107, 136));
        luasLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        luasLabel.setForeground(new java.awt.Color(139, 107, 105));
        luasLabel.setText("Luas");

        inputLuas.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        inputLuas.setText(" ");
        inputLuas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputLuasActionPerformed(evt);
            }
        });

        alamatLabel.setBackground(new java.awt.Color(77, 107, 136));
        alamatLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        alamatLabel.setForeground(new java.awt.Color(139, 107, 105));
        alamatLabel.setText("Jenis Lapangan");

        fasilitasLabel.setBackground(new java.awt.Color(77, 107, 136));
        fasilitasLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        fasilitasLabel.setForeground(new java.awt.Color(139, 107, 105));
        fasilitasLabel.setText("Fasilitas");

        statusLapanganLabel.setBackground(new java.awt.Color(77, 107, 136));
        statusLapanganLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        statusLapanganLabel.setForeground(new java.awt.Color(139, 107, 105));
        statusLapanganLabel.setText("Status Lapangan");

        saveBtn.setBackground(new java.awt.Color(139, 107, 105));
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(139, 107, 105));
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        sintetisRBtn.setBackground(new java.awt.Color(235, 226, 205));
        jenisLapanganBtnGroup.add(sintetisRBtn);
        sintetisRBtn.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        sintetisRBtn.setForeground(new java.awt.Color(255, 255, 255));
        sintetisRBtn.setText("Sintetis");
        sintetisRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sintetisRBtnActionPerformed(evt);
            }
        });

        plurRBtn.setBackground(new java.awt.Color(235, 226, 205));
        jenisLapanganBtnGroup.add(plurRBtn);
        plurRBtn.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        plurRBtn.setForeground(new java.awt.Color(255, 255, 255));
        plurRBtn.setText("Plur");
        plurRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plurRBtnActionPerformed(evt);
            }
        });

        bolaCBox.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        bolaCBox.setForeground(new java.awt.Color(255, 255, 255));
        bolaCBox.setText("Bola");

        rompiCBox.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        rompiCBox.setForeground(new java.awt.Color(255, 255, 255));
        rompiCBox.setText("Rompi");

        airMineralCBox.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        airMineralCBox.setForeground(new java.awt.Color(255, 255, 255));
        airMineralCBox.setText("Air Mineral");

        availableRBtn.setBackground(new java.awt.Color(235, 226, 205));
        statusLapanganBtnGroup.add(availableRBtn);
        availableRBtn.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        availableRBtn.setForeground(new java.awt.Color(255, 255, 255));
        availableRBtn.setText("Available");
        availableRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availableRBtnActionPerformed(evt);
            }
        });

        bookedRBtn.setBackground(new java.awt.Color(235, 226, 205));
        statusLapanganBtnGroup.add(bookedRBtn);
        bookedRBtn.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        bookedRBtn.setForeground(new java.awt.Color(255, 255, 255));
        bookedRBtn.setText("Booked");
        bookedRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookedRBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputPanelLayout = new javax.swing.GroupLayout(inputPanel);
        inputPanel.setLayout(inputPanelLayout);
        inputPanelLayout.setHorizontalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addComponent(sintetisRBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(plurRBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(inputLuas, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(inputId, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(inputNama, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(inputPanelLayout.createSequentialGroup()
                                    .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(statusLapanganLabel)
                                        .addComponent(luasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(namaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fasilitasLabel)
                                        .addComponent(alamatLabel))
                                    .addGap(0, 317, Short.MAX_VALUE)))
                            .addGroup(inputPanelLayout.createSequentialGroup()
                                .addComponent(cancelBtn)
                                .addGap(18, 18, 18)
                                .addComponent(saveBtn)))
                        .addGap(27, 27, 27))
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(inputPanelLayout.createSequentialGroup()
                                .addComponent(availableRBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bookedRBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(inputPanelLayout.createSequentialGroup()
                                .addComponent(bolaCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rompiCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(airMineralCBox)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        inputPanelLayout.setVerticalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(idLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(namaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(luasLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputLuas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(alamatLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sintetisRBtn)
                    .addComponent(plurRBtn))
                .addGap(25, 25, 25)
                .addComponent(fasilitasLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bolaCBox)
                    .addComponent(rompiCBox)
                    .addComponent(airMineralCBox))
                .addGap(22, 22, 22)
                .addComponent(statusLapanganLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(availableRBtn)
                    .addComponent(bookedRBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(cancelBtn))
                .addGap(15, 15, 15))
        );

        outputPanel.setBackground(new java.awt.Color(235, 226, 205));
        outputPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 107, 105), 1, true), "  Daftar Lapangan  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Berlin Sans FB Demi", 0, 18), new java.awt.Color(139, 107, 105))); // NOI18N

        lapanganTable.setBackground(new java.awt.Color(211, 199, 195));
        lapanganTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        lapanganTable.setSelectionBackground(new java.awt.Color(188, 153, 142));
        lapanganTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        lapanganTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lapanganTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lapanganTable);

        searchInput.setText(" ");

        searchBtn.setBackground(new java.awt.Color(139, 107, 105));
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        addBtn.setBackground(new java.awt.Color(139, 107, 105));
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        editBtn.setBackground(new java.awt.Color(139, 107, 105));
        editBtn.setForeground(new java.awt.Color(255, 255, 255));
        editBtn.setText("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(139, 107, 105));
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout outputPanelLayout = new javax.swing.GroupLayout(outputPanel);
        outputPanel.setLayout(outputPanelLayout);
        outputPanelLayout.setHorizontalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, outputPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(outputPanelLayout.createSequentialGroup()
                        .addComponent(addBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                        .addComponent(editBtn)
                        .addGap(33, 33, 33)
                        .addComponent(deleteBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, outputPanelLayout.createSequentialGroup()
                        .addComponent(searchInput)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchBtn))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        outputPanelLayout.setVerticalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editBtn)
                    .addComponent(deleteBtn)
                    .addComponent(addBtn))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout basePanelLayout = new javax.swing.GroupLayout(basePanel);
        basePanel.setLayout(basePanelLayout);
        basePanelLayout.setHorizontalGroup(
            basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basePanelLayout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(inputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(outputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );
        basePanelLayout.setVerticalGroup(
            basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basePanelLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(outputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60))
        );

        jScrollPane1.setViewportView(basePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

      
    private void inputIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIdActionPerformed
        
    }//GEN-LAST:event_inputIdActionPerformed

    private void inputNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNamaActionPerformed

    private void inputLuasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputLuasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputLuasActionPerformed

    private void sintetisRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sintetisRBtnActionPerformed
        if(sintetisRBtn.isSelected()){
            plurRBtn.setEnabled(false);
        }
    }//GEN-LAST:event_sintetisRBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        setComponent(true);
        clearText();        
        bookedRBtn.setEnabled(false);
        searchInput.setText("");
        action = "Tambah";
    }//GEN-LAST:event_addBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        setComponent(true);
        inputId.setEnabled(false);
        bookedRBtn.setEnabled(false);
        action = "Edit";
    }//GEN-LAST:event_editBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int getAnswer = JOptionPane.showConfirmDialog(rootPane, "Apakah yakini ingin menghapus data?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        
        if (getAnswer == JOptionPane.YES_NO_OPTION){
            try{
                lapanganControl.deleteDataLapangan(Integer.parseInt(inputId.getText()));
                clearText();
                showDataLapangan();
                setEditDeleteBtn(false);
                JOptionPane.showMessageDialog(null, " Data berhasil dihapus!");
            }catch(Exception e){
                System.out.println(e);}
        }else{
            JOptionPane.showMessageDialog(null,  "Data tidak jadi dihapus!");
            setComponent(false);
            showDataLapangan();
            setEditDeleteBtn(false);
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        try{
            String jenis = "";
            String fasilitas = "";
            String status = "";
            
            InputKosongException();
            jenisLapanganException();
            statusLapanganException();            
            
            if(sintetisRBtn.isSelected() == true){
                jenis = "Sintetis";                
            }else if(plurRBtn.isSelected()==true){
                jenis = "Plur";
            }
             if(availableRBtn.isSelected() == true){
                 status = "Available";
             }else if(bookedRBtn.isSelected() == true){
                 status = "Booked";
             }
             
             if(!bolaCBox.isSelected() && !rompiCBox.isSelected() && !airMineralCBox.isSelected()){
                 fasilitas = "-,-,-";
             }else if(bolaCBox.isSelected() && !rompiCBox.isSelected() && !airMineralCBox.isSelected()){
                 fasilitas = "Bola,-,-";
             }else if(!bolaCBox.isSelected() && rompiCBox.isSelected() && !airMineralCBox.isSelected()){
                 fasilitas = "-,Rompi,-";
             }else if(!bolaCBox.isSelected() && !rompiCBox.isSelected() && airMineralCBox.isSelected()){
                 fasilitas = "-,-,Air Mineral";
             }else if(bolaCBox.isSelected() && rompiCBox.isSelected() && !airMineralCBox.isSelected()){
                 fasilitas = "Bola,Rompi,-";
             }else if(bolaCBox.isSelected() && !rompiCBox.isSelected() && airMineralCBox.isSelected()){
                 fasilitas = "Bola,-,Air Mineral";
             }else if(!bolaCBox.isSelected() && rompiCBox.isSelected() && airMineralCBox.isSelected()){
                 fasilitas = "-,Rompi,Air Mineral";
             }else if(bolaCBox.isSelected() && rompiCBox.isSelected() && airMineralCBox.isSelected()){
                 fasilitas = "Bola,Rompi,Air Mineral";
             }
            
            if(action.equals("Tambah")){
                Lapangan l = new Lapangan(Integer.parseInt(inputId.getText()), inputNama.getText(), Integer.parseInt(inputLuas.getText()), jenis, fasilitas, status);
                lapanganControl.insertDataLapangan(l);
                JOptionPane.showMessageDialog(null, "Data Berhasil Ditambahkan");
            }else{
                Lapangan l = new Lapangan(selected, inputNama.getText(), Integer.parseInt(inputLuas.getText()), jenis, fasilitas, status);
                lapanganControl.updateDataLapangan(l,Integer.parseInt(inputId.getText()));
                JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
            }
            setComponent(false);
            setEditDeleteBtn(false);
            clearText();    
            showDataLapangan();
        }catch(InputKosongException e){
            JOptionPane.showMessageDialog(this, e.message());
        }catch(JenisLapanganException e1){
            JOptionPane.showMessageDialog(this, e1.message());
        }catch(StatusLapanganException e2){
            JOptionPane.showMessageDialog(this, e2.message());
        }catch(NumberFormatException e3){
            JOptionPane.showMessageDialog(this, "Input Invalid !");
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        setComponent(false);
        setEditDeleteBtn(false);
        clearText();        
        JOptionPane.showMessageDialog(null, "Batal !");
        
        lapanganTable.setModel(lapanganControl.showDataLapangan(""));
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        setEditDeleteBtn(true);
        setComponent(false);
        
        try{
            TableLapangan tl = lapanganControl.showDataLapangan(searchInput.getText());
            if(tl.getRowCount()==0){
                clearText();
                setEditDeleteBtn(false); 
                JOptionPane.showMessageDialog(null,"Data tidak ditemukan", "Konfirmasi", JOptionPane.DEFAULT_OPTION);
            }else{
                lapanganTable.setModel(tl);
            }
            clearText();
            cancelBtn.setEnabled(true);
        }catch(Exception e){
            System.out.println("Error : " +e.getMessage());
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void plurRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plurRBtnActionPerformed
        
    }//GEN-LAST:event_plurRBtnActionPerformed

    private void availableRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availableRBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availableRBtnActionPerformed

    private void bookedRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookedRBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookedRBtnActionPerformed

    private void lapanganTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lapanganTableMouseClicked
        setEditDeleteBtn(true);
        setComponent(false);
        
        int clickedRow = lapanganTable.getSelectedRow();
        TableModel tableModel = lapanganTable.getModel();
        
        inputId.setText(tableModel.getValueAt(clickedRow, 0).toString());
        inputNama.setText(tableModel.getValueAt(clickedRow, 1).toString());
        inputLuas.setText(tableModel.getValueAt(clickedRow, 2).toString());
        String jenis = tableModel.getValueAt(clickedRow, 3).toString();
        String fasilitas = tableModel.getValueAt(clickedRow, 4).toString();
        String status = tableModel.getValueAt(clickedRow, 5).toString();
        
        switch(jenis){
            case "Sintetis":
                sintetisRBtn.setSelected(true);
                plurRBtn.setSelected(false);
                break;
            case "Plur":
                sintetisRBtn.setSelected(false);
                plurRBtn.setSelected(true);
                break;
            default :
                sintetisRBtn.setSelected(false);
                plurRBtn.setSelected(false);
                break;
        }
        
        if(!bolaCBox.isSelected() && !rompiCBox.isSelected() && !airMineralCBox.isSelected()){
            bolaCBox.setSelected(false);
            rompiCBox.setSelected(false);
            airMineralCBox.setSelected(false);
        }else if(bolaCBox.isSelected() && !rompiCBox.isSelected() && !airMineralCBox.isSelected()){
            bolaCBox.setSelected(true);
            rompiCBox.setSelected(false);
            airMineralCBox.setSelected(false);
        }else if(!bolaCBox.isSelected() && rompiCBox.isSelected() && !airMineralCBox.isSelected()){
            bolaCBox.setSelected(false);
            rompiCBox.setSelected(true);
            airMineralCBox.setSelected(false);
        }else if(!bolaCBox.isSelected() && !rompiCBox.isSelected() && airMineralCBox.isSelected()){
            bolaCBox.setSelected(false);
            rompiCBox.setSelected(false);
            airMineralCBox.setSelected(true);
        }else if(bolaCBox.isSelected() && rompiCBox.isSelected() && !airMineralCBox.isSelected()){
            bolaCBox.setSelected(true);
            rompiCBox.setSelected(true);
            airMineralCBox.setSelected(false);
        }else if(bolaCBox.isSelected() && !rompiCBox.isSelected() && airMineralCBox.isSelected()){
            bolaCBox.setSelected(true);
            rompiCBox.setSelected(false);
            airMineralCBox.setSelected(true);
        }else if(!bolaCBox.isSelected() && rompiCBox.isSelected() && airMineralCBox.isSelected()){
            bolaCBox.setSelected(false);
            rompiCBox.setSelected(true);
            airMineralCBox.setSelected(true);
        }else if(bolaCBox.isSelected() && rompiCBox.isSelected() && airMineralCBox.isSelected()){
            bolaCBox.setSelected(true);
            rompiCBox.setSelected(true);
            airMineralCBox.setSelected(true);
        }
        
        switch(status){
            case "Available":
                availableRBtn.setSelected(true);
                bookedRBtn.setSelected(false);
                break;
            case "Booked":
                availableRBtn.setSelected(false);
                bookedRBtn.setSelected(true);
                break;
            default :
                availableRBtn.setSelected(false);
                bookedRBtn.setSelected(false);
                break;
        }
        
        cancelBtn.setEnabled(true);
    }//GEN-LAST:event_lapanganTableMouseClicked
   
    private void karyawanPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_karyawanPanelMouseClicked
        ViewKaryawan vk = new ViewKaryawan();
        this.dispose();
        vk.setVisible(true);
    }//GEN-LAST:event_karyawanPanelMouseClicked

    private void lapanganPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lapanganPanelMouseClicked
        ViewLapangan vl = new ViewLapangan();
        this.dispose();
        vl.setVisible(true);
    }//GEN-LAST:event_lapanganPanelMouseClicked

    private void bookingPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingPanelMouseClicked
        ViewBooking vb = new ViewBooking();
        this.dispose();
        vb.setVisible(true);
    }//GEN-LAST:event_bookingPanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewLapangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewLapangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewLapangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewLapangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewLapangan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JCheckBox airMineralCBox;
    private javax.swing.JLabel alamatLabel;
    private javax.swing.JRadioButton availableRBtn;
    private javax.swing.JPanel basePanel;
    private javax.swing.JCheckBox bolaCBox;
    private javax.swing.JRadioButton bookedRBtn;
    private javax.swing.JLabel bookingIcon;
    private javax.swing.JLabel bookingLabel;
    private javax.swing.JPanel bookingPanel;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel fasilitasLabel;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField inputId;
    private javax.swing.JTextField inputLuas;
    private javax.swing.JTextField inputNama;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.ButtonGroup jenisLapanganBtnGroup;
    private javax.swing.JLabel karyawanIcon;
    private javax.swing.JLabel karyawanLabel;
    private javax.swing.JPanel karyawanPanel;
    private javax.swing.JLabel lapanganIcon;
    private javax.swing.JLabel lapanganLabel;
    private javax.swing.JPanel lapanganPanel;
    private javax.swing.JTable lapanganTable;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JLabel luasLabel;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JPanel outputPanel;
    private javax.swing.JRadioButton plurRBtn;
    private javax.swing.JCheckBox rompiCBox;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchInput;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JRadioButton sintetisRBtn;
    private javax.swing.ButtonGroup statusLapanganBtnGroup;
    private javax.swing.JLabel statusLapanganLabel;
    // End of variables declaration//GEN-END:variables

}
